require "bundler"

begin
  Bundler.setup(:default, :development)
rescue Bundler::BundlerError
  $stderr.puts $!.message
  $stderr.puts "Run `bundle install` to install missing gems"
  exit $!.exit_code
end

require "rake"

require "rspec/core"
require "rspec/core/rake_task"
RSpec::Core::RakeTask.new(:spec) do |spec|
  spec.pattern = FileList['spec/**/*_spec.rb']
end

task :default => :spec

